version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # volumes:
    # - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev

  my-redis:
    image: redis:latest
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  logstash:
    image: logstash:7.17.0
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
      - ./elk/logstash/template.json:/usr/share/logstash/template.json
